### ISSUE TITLE
volttron 10.0.1a24 does not seem to honor $VOLTTRON_HOME

### ISSUE THREAD

**Issue by davidraker** [eclipse-volttron/volttron-core#79]
Using volttron-core 10.0.1a24, starting VOLTTRON from volttron-lib-web gives error on startup, indicating that it is not honoring VOLTTRON_HOME:

(.venv) volttron@volttron1:\~/git/volttron-web-service$ volttron -vv
2022-10-10 15:30:18,218 () volttron.server.__main__(226) DEBUG: opts.instancename volttron1
2022-10-10 15:30:18,218 () volttron.server.__main__(285) DEBUG: open file resource limit 1048576 to 1048576
Traceback (most recent call last):
  File "/home/volttron/git/volttron-web-service/.venv/bin/volttron", line 8, in <module>
    sys.exit(main())
  File "/home/volttron/git/volttron-web-service/.venv/lib/python3.8/site-packages/volttron/server/__main__.py", line 1066, in main
    start_volttron_process(opts)
  File "/home/volttron/git/volttron-web-service/.venv/lib/python3.8/site-packages/volttron/server/__main__.py", line 288, in start_volttron_process
    opts.aip.setup()
  File "/home/volttron/git/volttron-web-service/.venv/lib/python3.8/site-packages/volttron/server/aip.py", line 420, in setup
    with open(os.path.join(self.install_dir, vip_id, "UUID"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/volttron/.volttron/agents/9e0650c2-7b6f-43a3-9ff1-a280be2b2cbb/UUID'
(.venv) volttron@volttron1:\~/git/volttron-web-service$ echo $VOLTTRON_HOME
/home/volttron/.volttron-web
(.venv) volttron@volttron1:~/git/volttron-web-service$

**Comment by craig8** [comment]
this isn't an agent it's a lib so you need to pip install it not install it as an agent.

**Comment by craig8** [comment]
poetry build
poetry run pip install dist/*.whl

or something like that

**Comment by davidraker** [comment]
@craig8 The problem was in my environment, though I'm not sure what. As long as I'm not using the terminal inside the IDE, this works fine.
